#!/bin/bash


#############################################################
##################### PROCESSING STEPS #####################
#############################################################

####### fMRIPrep outputs that pass QA #######
# QA: Prior manual + Euler-based inspection for unchecked images
# Assume csv of form: bblid,seslabel,t1RawDataExclude,cnr_graycsflh,cnr_graycsfrh,
# cnr_graywhitelh,cnr_graywhiterh,euler_lh,euler_rh


######## Find relevant files/paths ########
InDir=/data
subj=`ls ${InDir}/ | sed 's#.*/##'`
t1wimages=`find ${InDir}/${subj}/ses*/fmriprep/${subj}/anat -name "${subj}_desc-preproc_T1w.nii.gz"`
sessions=`ls -d ${InDir}/${subj}/ses* | sed 's#.*/##'`

######## Make output directory ########

OutDir=/home
mkdir ${OutDir}/${subj}
for ses in ${sessions}; do
  mkdir -p ${OutDir}/${subj}/${ses}/anat;
done

######## Run Template Construction ########
# On bias-field corrected, but not skull-stripped, image

for image in ${t1wimages}; do echo "${image}" >> ${OutDir}/tmp_subjlist.csv ; done

antsMultivariateTemplateConstruction.sh -d 3 -o "${OutDir}/${subj}/" -n 0 -c 2 -j 2 ${OutDir}/tmp_subjlist.csv

######## Rename files as appropriate ########

for ses in ${sessions} ; do
  mv ${OutDir}/${subj}/*_${ses}_* ${OutDir}/${subj}/${ses}/anat;
done

mkdir ${OutDir}/${subj}/scripts
mv ${OutDir}/${subj}/*.sh ${OutDir}/${subj}/scripts
mv ${OutDir}/${subj}/template0.nii.gz ${OutDir}/${subj}/${subj}_template0.nii.gz
mv ${OutDir}/${subj}/templatewarplog.txt ${OutDir}/${subj}/${subj}_templatewarplog.txt
mv ${OutDir}/${subj}/template0Affine.txt ${OutDir}/${subj}/${subj}_template0Affine.txt
mv ${OutDir}/${subj}/template0warp.nii.gz ${OutDir}/${subj}/${subj}_template0warp.nii.gz


######## Remove unnecessary files ########

rm ${OutDir}/tmp_subjlist.csv



#############################################################
#############################################################
#############################################################
